platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets
- name: release
- name: app-info

outputs:
- name: manifest-output

run:
  path: git-assets/pipeline/scripts/generate-manifest.sh
