---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets
- name: app-info

outputs:
- name: app-route

run:
  path: git-assets/pipeline/scripts/update-route.sh